config/routes.rb
Rails.application.routes.draw do

   root 'home#upload_csv'
   resources :companies do
     collection do
        get 'search'
      end
   end
    get 'home/upload_csv' => 'home#upload_csv'
    post 'home/upload_url' => 'home#upload_url'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :operations
  validates_presence_of :name
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :operations

  validates_presence_of :name
  def self.find_company(id)
    company = Company.find_by_id(id)
  end
  def number_of_operations
     self.operations.count
  end
  def avg_amount_operation
     self.operations.average(:amount)
  end
  def  max_amount_of_opt
     self.operations.map(&:amount).max
  end
  def  no_of_opt_status_accepted
     self.operations.where(:status => "accepted").count
  end

  def to_csv(options = {})
    column_names = %w{invoice_num invoice_date operation_date amount reporter notes status kind }
    company_column_name = %w{company}
    company_name = %w{name}
    CSV.generate(options) do |csv|
      csv.add_row column_names + company_column_name

      self.operations.each do |opt|

        values = opt.attributes.slice(*column_names).values

        if opt.company
          values += opt.company.attributes.slice(*company_name).values
        end

        csv.add_row values
      end
    end
  end

  def self.search(search)
     Operation.where('lower(status) LIKE :search OR lower(kind) LIKE :search OR lower(invoice_num) LIKE :search OR lower(reporter) LIKE :search', search: "%#{search.downcase}%")
  end

end

app/models/operation.rb
class Operation < ActiveRecord::Base
  has_and_belongs_to_many :categories
  belongs_to :company

  validates_presence_of :invoice_num, :invoice_date, :amount, :operation_date, :kind, :status
  validates_numericality_of :amount, greater_than: 0
  validates_uniqueness_of :invoice_num
  def self.opt_count
    self.all.count
  end

  def self.no_of_imp_row
    self.where.not(:company_id => 0).count
  end

  def self.no_of_failed_row
    self.where(:company_id => 0).count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # We don't want to overcomplicate, so let this be just disabled
  # protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
require 'csv'
class CompaniesController < ApplicationController
  helper CompaniesHelper
  def index
    @companies = Company.all
  end

  def search
     @search_results = Company.search(params["search"]).paginate(page: params[:page], per_page: 25)
     respond_to do |format|
       format.js # search.js.erb
     end
  end

  def show
    @company = Company.find_company(params["id"])
    @no_of_operations = @company.number_of_operations
    @avg_amount_operation = @company.avg_amount_operation
    @max_amount_of_opt = @company.max_amount_of_opt
    @no_of_opt_status_accepted = @company.no_of_opt_status_accepted
    respond_to do |format|
      #format.html # show.html.erb
      format.js # show.js.erb
      format.csv { send_data @company.to_csv, filename: "company-#{Date.today}.csv" }
    end
  end
end

app/controllers/home_controller.rb
require 'csv'
class HomeController < ApplicationController
  before_filter :operation_check, :only => [:upload_url]
  def index

  end
  def upload_csv
     @operations = Operation.all
     @operations_count = Operation.opt_count
     @import_successed_rows = Operation.no_of_imp_row
     @import_failed_rows= Operation.no_of_failed_row
  end
  def upload_url
    if params[:file_path].present?
     CSV.foreach(params[:file_path].path, headers: true, encoding: 'ISO-8859-1:UTF-8') do |row|
       a = row.to_hash
       company = Company.find_by_name(a['company'].lstrip.rstrip)  if !a['company'].nil?
       company_id = company.nil? ? 0 : company.id
       Operation.create(
           :invoice_num => a['invoice_num'],
           :invoice_date => a['invoice_date'],
           :operation_date => a['operation_date'],
           :amount => a['amount'],
           :reporter => a['reporter'],
           :notes => a['notes'],
           :status => a['status'],
           :kind => a['kind'],
           :company_id => company_id
       )
      kind_downcase = a['kind'].downcase.split(";").sort! if !a['kind'].nil?
      kind_arr_str =  kind_downcase.join(";")  if !kind_downcase.nil?
       Category.find_or_create_by(
          :name => kind_arr_str
       )

  end
    redirect_to home_upload_csv_path
    else
      flash[:alert] = "Please Upload a file"
      redirect_to home_upload_csv_path
   end

  end

  def operation_check
   if Operation.all.empty?
     return true
   else
     flash[:alert] = "Could not upload CSV More than once"
     redirect_to home_upload_csv_path
   end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def company_operations(com_id)
     operations =  Operation.where(:company_id => com_id).order("operation_date ASC").map(&:id).first(5)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/will_paginate_helper.rb
module WillPaginateHelper
  class WillPaginateJSLinkRenderer < WillPaginate::ActionView::LinkRenderer
    def prepare(collection, options, template)
      options[:params] ||= {}
      options[:params]['_'] = nil
      super(collection, options, template)
    end

    protected
    def link(text, target, attributes = {})
      if target.is_a? Fixnum
        attributes[:rel] = rel_value(target)
        target = url(target)
      end

      @template.link_to(target, attributes.merge(remote: true)) do
        text.to_s.html_safe
      end
    end
  end

  def js_will_paginate(collection, options = {})
    will_paginate(collection, options.merge(:renderer => WillPaginateHelper::WillPaginateJSLinkRenderer))
  end
end

app/views/companies/_company.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-body">
      <table class="table table-striped">
        <tr>
          <th><h4>Details of Operations</h4></th>
          <th> <h4> Count </h4></th>
        </tr>
        <tr>
          <td>
            <h5 class="panel-title">
              Number Of Operation
            </h5>
          </td>
          <td>
            <%= @no_of_operations%>
          </td>
        </tr>
        <tr>
          <td>
            <h5 class="panel-title">
              Average amount Of Operation
            </h5>
          </td>
          <td>
            <%= @avg_amount_operation%>
          </td>
        </tr>
        <tr>
          <td>
            <h5 class="panel-title">
              Highest amount of operations
            </h5>
          </td>
          <td>
            <%= @max_amount_of_opt%>
          </td>
        </tr>
        <tr>
          <td>
            <h5 class="panel-title">
              Number of operations with status Accepted
            </h5>
          </td>
          <td>
            <%= @no_of_opt_status_accepted%>
          </td>
        </tr>
      </table>

      <span> <%= link_to "Download CSV", company_path(format: "csv"), class: "btn btn-primary" %>
</span>
    </div>
  </div>
</div>

app/views/companies/_dialog.html.erb
<div class="modal fade"
     id="dialog" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel"
     aria-hidden="true"
     data-backdrop="static"
     data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close"
                data-dismiss="modal"
                aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/companies/_search_result.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2>Search Results </h2>
    <div class="panel-body">
      <table class="table table-striped">
        <tr>
          <th><h4>Operation ID</h4></th>
          <th><h4>Invoice Number</h4></th>
          <th><h4>Invoice Date</h4></th>
          <th><h4>Status</h4></th>
          <th><h4>Category</h4></th>
          <th><h4>Reporter</h4></th>
          <th><h4>Company Name</h4></th>
        </tr>
        <% search_results.each do |result| %>
            <tr>
              <td>
                          <%= "Operation #{result.id}"%>
              </td>
              <td>
                    <%= result.invoice_num%>
              </td>
              <td>
                    <%= result.invoice_date%>
              </td>
              <td>
                    <%= result.status%>
              </td>
              <td>
                    <%= result.kind%>
              </td>
              <td>
                    <%= result.reporter%>
              </td>
              <td>
                    <%= result.company.nil? ? "Undefined" : result.company.name %>
              </td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>
<%= js_will_paginate search_results, :params => { :my_excluded_param => nil } %>

app/views/companies/index.html.erb
     <%= render partial: 'dialog'%>
     <%= form_tag(search_companies_path(format: :js), method: "get", id: "search-form", class:"navbar-form navbar-right", :remote => true) do %>
         <div class="input-group"> <%= text_field_tag :search, params[:search], placeholder: "Search Text", class: "form-control" %>
           <span class="input-group-btn">
         <%= submit_tag "Search",  class:"btn btn-default", page: 1 %>
             <span class="glyphicon glyphicon-search"></span>
               </span>
             </div>
     <% end %>
     <br/><br/><br/>

<div id="search_result">

</div>
<div id="company_index">
<div class="panel panel-default">
  <div class="panel-heading">
    <h2>Company Lists With Operations</h2>
    <div class="panel-body">
      <table class="table table-striped">

        <% @companies.each do |company| %>
            <tr>
              <td>
                <div class="panel panel-default">
                  <div class="panel-heading" role="tab" id="heading<%= company.id%>">
                    <h4 class="panel-title">
                      <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= company.id%>" aria-expanded="true" aria-controls="collapse<%= company.id%>">
                        <%= company.name%>
                      </a>
                    </h4>
                  </div>
                  <div id="collapse<%= company.id%>" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading<%= company.id%>">
                    <div class="panel-body">
                      <%company_operations(company.id).each do |operation| %>
                          <%= "Operation #{operation}"%>
                          <br>
                      <%end%>
                    </div>
                  </div>
                </div>
              </td>

              <td>
                <div class="glyphicon glyphicon-eye-open"></div>
                <%= link_to "#{company.name} Stats", company, :remote => true %>
              </td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>
</div>

app/views/companies/search.js.erb
$("#search_result").css("display", "block");
$("#search_result").html("<%= escape_javascript(render partial: 'search_result', locals: { search_results: @search_results} ) %>");
$("#company_index").css("display", "none");

app/views/companies/show.js.erb
$('#dialog h3').html("<i class='glyphicon'></i> Company Details");
 console.log("its working");
$(".modal-body").html("<%= escape_javascript(render partial: 'company', locals: { no_of_operations: @no_of_operations, avg_amount_operation: @avg_amount_operation, max_amount_of_opt: @max_amount_of_opt, no_of_opt_status_accepted: @no_of_opt_status_accepted} ) %>");

$('#dialog').modal("show");

app/views/home/_form.html.erb
<%= form_tag '/home/upload_url', multipart: true do  %>
    <div class="row">
      <div class="col-md-3">
        <%= file_field_tag :file_path,accept: 'text/csv'%>
        <br>
        <%= submit_tag "Upload", class: "btn btn-primary"%>
      </div>
    </div>
<% end %>

app/views/home/index.html.erb
<% flash.each do |key, value| %>
    <%= "test"%>
    <div class="alert alert-danger"><%= value %></div>
<% end %>

app/views/home/upload_csv.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-danger alert-<%= key %>"><%= value %></div>
<% end %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>CSV Upload</h3>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-body">
<% unless @operations.empty? %>
    <table class="table table-striped">
      <tr>
        <th><h4>Details of File Processed</h4></th>
        <th> <h4> Count </h4></th>
      </tr>
      <tr>
        <td>
          <h5 class="panel-title">
            Number Of Processed Rows
          </h5>
        </td>
        <td>
          <%= @operations_count%>
        </td>
      </tr>
      <tr>
        <td>
          <h5 class="panel-title">
            Number of Successfully Imported Rows
          </h5>
        </td>
        <td>
          <%= @import_successed_rows%>
        </td>
      </tr>
      <tr>
        <td>
          <h5 class="panel-title">
            Number of Failed Imported Rows
          </h5>
        </td>
        <td>
          <%= @import_failed_rows%>
        </td>
      </tr>
    </table>
    <%end%>
   </div>
  </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <title>ImportApp</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application"  %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "shared/header" %>
<div class="page_content">
  <div class="container">
    <%= yield     %>
  </div>
</div>
<%= render partial: "shared/footer" %>
</body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <hr/>
      <div class="tleft">
        &copy; 2015 Import APP
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <!--/ place your website logo here
      -->
      <a class="navbar-brand" href="<%= root_path %>">
        <div class="glyphicon glyphicon-flag"></div>
        Import App
      </a>
    </div>
    <div class="pull-right twitter_btn">
          <div>
          <%#= link_to "Import CSV", home_upload_csv_path , class: "btn btn-primary btn-sm", style: "margin-right:10px;"         %>
          <%= link_to "Companies List", companies_path , class: "btn btn-primary btn-sm" %>
         </div>
     </div>
  </div>
</nav>